name: Publish

on:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
      - 'examples/**'
      - 'tests/**'
      - '*.tf'
      - '*.md'
      - 'version'
      - '.github/workflows/publish.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0
      
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate
